# This is a converted version of config.py
# I'm keeping both around for now, as we transition.

labels:
  - Congestion or runny nose
  - Cough
  - Diarrhea
  - Dyspnea
  - Fatigue
  - Fever or chills
  - Headache
  - Loss of taste or smell
  - Muscle or body aches
  - Nausea or vomiting
  - Sore throat

annotators:
  andy = 2
  amy = 3
  alon = 6
  ctakes = 7  # mcmurry.andy
  icd10 = 0

ranges:
  corpus: 782-1006
  amy: 782-895
  andy: 895-1006
  andy_alon: 979-1006
  amy_alon: 864-891
  alon: [amy_alon, andy_alon]
  icd10_missing: [782, 791, 793, 799, 811, 824, 826, 828, 833, 837, 859, 860, 870, 877, 882, 886, 921, 959, 985, 986, 994, 1004]
