name: CI
on:
  pull_request:
  push:
    branches:
      - main

# The goal here is to cancel older workflows when a PR is updated (because it's pointless work)
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  unittest:
    name: unit tests
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        # don't go crazy with the Python versions as they eat up CI minutes
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[tests]

      - name: Test with pytest
        run: |
          python -m pytest

  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install linters
        # black is synced with the .pre-commit-hooks version
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Run pycodestyle
        # E203: pycodestyle is a little too rigid about slices & whitespace
        #  See https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#slices
        # W503: a default ignore that we are restoring
        run: |
          pycodestyle --max-line-length=100 --ignore=E203,W503 .

      - name: Run bandit
        if: success() || failure() # still run bandit if above checks fail
        run: |
          bandit -c pyproject.toml -r .

      - name: Run black
        if: success() || failure() # still run black if above checks fails
        run: |
          black --check --verbose .
